.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/deploy.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, pom.xml, src/test/kotlin/org/camunda/community/zeebe/play/ApplicationTests.kt, src/test/kotlin/org/camunda/community/zeebe/play/GraphqlApiTests.kt, src/test/kotlin/org/camunda/community/zeebe/play/WebAppTests.kt
* enable GitHub CI
* clean up Maven pom.xml
* fix test case
=> Setup project

src/main/kotlin/org/camunda/community/zeebe/play/rest/DemoResource.kt, src/main/resources/public/js/view-home.js, src/main/resources/templates/views/home.html
On loading the home view, enable the button to create a process instance if the demo process is deployed.
closes #7
=> feat: enable button if demo process is deployed

src/main/resources/public/js/view-bpmn.js, src/main/resources/public/js/view-process-instance.js, src/main/resources/templates/views/monitoring/process-instances/process-instance.html
* use icons for element instance state
* show counter only if greater than zero
* add button to show all element counters
closes #20
=> feat: show icons for the element instance state

src/main/resources/public/js/view-common.js, src/main/resources/public/js/view-monitoring.js, src/main/resources/public/js/view-process-instance.js
* add icon to highlight element in diagram
* add icon to show variable updates
* add icon to show state transitions
* add icon to show correlated messages
* add icon to show error details
* add icon to show correlated process instances
=> feat: Improve design by adding more icons

pom.xml
* bundle MySQL driver for Zeebe-Play
closes #39
=> build: bundle MySQL driver

src/main/resources/templates/views/new-deployment-modal.html
* only accept .bpmn, .xml, and .dmn files for deployments
closes #84
=> feat: only accept .bpmn, .xml, and .dmn files for deployments

src/main/resources/demo/solos-transport-process.bpmn, src/main/resources/public/js/view-home.js, src/main/resources/templates/views/home.html
We want to highlight the new Camunda form integration. Mention the new feature on the home view.
Update the demo process and add a form to the user task `Load cargo`. The form sets the variable `cargo`. The variable `cargo` is not set initially on instance creation anymore.
=> Highlight user forms on the home view and the demo process

src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorService.kt, src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorsConfig.kt, src/main/kotlin/org/camunda/community/zeebe/play/rest/ConnectorsResource.kt, src/main/resources/public/js/rest-client.js, src/main/resources/public/js/view-connectors.js, src/main/resources/templates/views/connectors/available-connectors.html, src/main/resources/templates/views/connectors/connector-secrets.html, src/main/resources/templates/views/connectors/connectors.html
Add a new view to the UI to show the available connectors. 
related to #30
=> I can see the available connectors

src/main/resources/templates/views/home.html
Highlight the integration of connectors on the home page.
=> feat: Highlight connectors on the home page

src/main/resources/public/js/view-process-instance.js, src/main/resources/public/js/view-process.js, src/main/resources/public/js/view-processes.js, src/main/resources/public/js/zeeqs-client.js
Reload the deployment (i.e. process) page if a new process is deployed or if the state of a process instance changed (i.e. created, completed, terminated). 
related to #12
=> feat: Auto reload for the deployment page

src/main/resources/templates/views/home.html
Highlight the new rewind feature on the home page.
=> feat: Highlight the new rewind feature

.gitignore, src/main/kotlin/org/camunda/community/zeebe/play/rest/RuntimeExceptionHandler.kt, src/main/kotlin/org/camunda/community/zeebe/play/rest/ServiceFailure.kt, src/main/resources/public/js/view-common.js
Improve the UI for command rejections. Hide the (technical) details of the rejection in a collapsed box. 
---
---
=> Improve rejection message

src/main/resources/public/js/view-bpmn.js, src/main/resources/public/js/view-process-instance.js
* preserve diagram position on page reload
closes #123
=> feat: preserve diagram position on page reload

src/main/kotlin/org/camunda/community/zeebe/play/rest/StatusResource.kt, src/main/resources/public/js/rest-client.js, src/main/resources/public/js/view-home.js, src/main/resources/templates/views/home.html
Show the following data on the home page:
* the version of Zeebe-Play
* the version of the Zeebe engine (i.e. EZE)
* the status of the Zeebe engine
=> feat: Show version and status

src/main/resources/public/js/view-common.js, src/main/resources/public/js/view-process-instance.js, src/main/resources/templates/views/monitoring/process-instances/process-instance-details-user-tasks.html, src/main/resources/templates/views/monitoring/process-instances/process-instance-details.html
Show all user tasks of a process instance.
closes #67
=> feat: Show user tasks of process instance

src/main/resources/public/js/incident-modal.js, src/main/resources/public/js/tracking.js, src/main/resources/public/js/view-home.js, src/main/resources/public/js/view-process-instance.js, src/main/resources/public/js/view-process.js, src/main/resources/templates/fragments/footer.html
This PR adds integration to mixpanel to track some events. The tracking is only active if an identifier object is provided via a special hash in the URL.
closes #141
=> feat: add mixpanel tracking

src/main/resources/public/js/view-common.js
Reload the page after a max delay of 450 ms.
=> feat: Reduce time to reload

src/main/kotlin/org/camunda/community/zeebe/play/rest/DemoResource.kt, src/main/resources/demo/is_legal_good.dmn, src/main/resources/demo/load-cargo.form, src/main/resources/demo/solos-transport-process.bpmn, src/main/resources/public/js/view-home.js, src/main/resources/templates/views/home.html
* Highlight new DMN features on the home page
* Include DMN in the demo process
=> feat: Highlight DMN

src/main/kotlin/org/camunda/community/zeebe/play/rest/ProcessesResource.kt, src/main/kotlin/org/camunda/community/zeebe/play/rest/SignalResource.kt, src/main/resources/public/js/rest-client.js, src/main/resources/public/js/view-bpmn.js, src/main/resources/public/js/view-common.js, src/main/resources/public/js/view-process-instance.js, src/main/resources/public/js/view-process.js, src/main/resources/public/js/zeeqs-client.js, src/main/resources/templates/views/deployment/process/process-details-signal-subscriptions.html, src/main/resources/templates/views/deployment/process/process-details.html, src/main/resources/templates/views/deployment/process/process.html, src/main/resources/templates/views/modals/broadcast-signal-modal.html
Show signal subscription of a process. Be able to broadcast a signal from the diagram or from the tab view.
closes #148
=> feat: Add support for signal start events

src/main/resources/public/css/form-js.css, src/main/resources/public/js/form-viewer.umd.js
* Update form-js dependency to [`v1.0.0`](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js/CHANGELOG.md#100)
Related to https://github.com/camunda/team-hto/issues/286
=> feat: update to form-js@1.0.0

src/main/resources/public/css/form-js.css, src/main/resources/public/js/form-viewer.umd.js
* Updates form-js to version 1.1.0
Changelog: https://github.com/bpmn-io/form-js/blob/develop/packages/form-js/CHANGELOG.md#110
closes #
=> feat: update to form-js@1.1.0

src/main/resources/public/css/form-js.css, src/main/resources/public/js/form-viewer.umd.js
Bumps form-js dependency to 1.3.0, which includes the new Group component 🎉 
Related to https://github.com/camunda/team-hto/issues/351
=> feat: update to form-js@1.3.0

src/main/resources/public/css/form-js.css, src/main/resources/public/js/form-viewer.umd.js
Related to camunda/team-hto#372
=> chore: Bump form-js to 1.4.0
