src/main/resources/public/js/view-process.js
* the view of correlated messages of a message start event was broken if the process has more than one message start event
closes #21
=> fix: View correlated messages of a message start event

src/main/resources/public/js/view-process-instance.js
- remove all parent elements from breadcrumb before adding the elements
closes #19
=> fix: breadcrumb on child process instance

src/main/resources/public/js/view-bpmn.js
- move the button to jump to the child process instance to the right top corner
- move the info button for activities and sequence flows to the right bottom corner
closes #18
=> fix: Resolve incident on call activity

pom.xml, src/main/resources/public/js/view-common.js, src/main/resources/public/js/zeeqs-client.js
I can  see the following properties of a user task:
- assignee
- candidate groups
closes #17
=> feat: show the properties of a user task

src/main/resources/public/js/view-process-instance.js, src/main/resources/public/js/zeeqs-client.js
Fetch user tasks of the process instance from ZeeQS. Add a marker for each active user task. Remove the marker from not active tasks.
Fix the demo process by making the user tasks completable again.
Related to #10
=> feat: load user tasks of process instance

src/main/resources/public/img/edit-form.svg, src/main/resources/public/js/task-form.js, src/main/resources/public/js/view-bpmn.js, src/main/resources/public/js/view-process-instance.js, src/main/resources/public/js/zeeqs-client.js
This PR changes the way user task forms get their form markup and variables and replaces the previous hacky implementation with the proper one, getting the data from Zeeqs thanks to https://github.com/camunda-community-hub/zeeqs/issues/284
It also changes the complete job UI for user tasks, adding a dedicated form icon and removing the fail and error options from the dropdown because they are not valid options for a user task (for now).
closes #10
=> User Task Forms UI and data fetching

src/main/resources/public/js/view-common.js, src/main/resources/public/js/view-process-instance.js, src/main/resources/public/js/view-process.js
This should reduce the number of times where the next job is not marked as active yet so that the user does not have to manually refresh the data as often.
related to #12
=> feat: add slight delay when fetching data after job completion

src/main/resources/public/js/view-common.js, src/main/resources/public/js/view-process-instance.js, src/main/resources/public/js/view-process.js, src/main/resources/public/js/zeeqs-client.js, src/main/resources/templates/views/deployment/process/process.html, src/main/resources/templates/views/monitoring/process-instances/process-instance.html
This adds a graphql subscription to process instance updates so that the UI is reloaded automatically when anything changes. The UI update is debounced by 150ms because often multiple update notifications come in at the same time (e.g. if a job completion also triggers the completion of subsequent flow nodes). Debouncing the update ensures that the UI is reloaded only once after all those updates have completed so that the client does not trigger unnecessary requests.
closes #12
=> feat: The UI is reloaded automatically

src/main/resources/public/js/zeeqs-client.js
I could not really test it, but I am fairly certain that we need to use the `wss` protocol if Zeebe Play is running via an ssl encrypted connection.
related to #12
=> fix: use proper websocket protocol for ssl encrypted connections

pom.xml, src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorProperties.kt, src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorSecret.kt, src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorSecretRepository.kt, src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorsConfig.kt, src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorsSecretProvider.kt, src/main/kotlin/org/camunda/community/zeebe/play/rest/ConnectorSecretsResource.kt, src/main/kotlin/org/camunda/community/zeebe/play/ui/ConnectorsView.kt, src/main/resources/application.yml, src/main/resources/public/js/rest-client.js, src/main/resources/public/js/view-connectors.js, src/main/resources/templates/fragments/footer.html, src/main/resources/templates/fragments/navbar.html, src/main/resources/templates/views/connectors/connectors.html, src/main/resources/templates/views/connectors/edit-connector-secret-modal.html, src/main/resources/templates/views/connectors/new-connector-secret-modal.html
Bundles Camunda connectors (version `0.15.0`) into Zeebe-Play. The connectors are started when the application is started.
Add a new database repository to store the connector secrets. Add a new page to the UI to see and modify the secrets.
The connectors can be disabled in the config:
```yaml
zeebe:
client:
connectors:
enabled: false  
```
Initial secrets can be defined in the config:
```yaml
zeebe:
client:
connectors:
secrets:
- name: SLACK_OAUTH_TOKEN
value: my-slack-oauth-token  
```
The new REST API could be used to set the connector secrets from outside:
```
curl \
-X POST \
-H "Content-Type: application/json" \
--data '{ "secrets": [{"name": "SLACK_OAUTH_TOKEN", "value": "my-token"}] }' \
http://localhost:8080/rest/connector-secrets
```
closes #30
=> Bundle Camunda connectors

src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorService.kt, src/main/kotlin/org/camunda/community/zeebe/play/rest/ConnectorSecretsResource.kt, src/main/kotlin/org/camunda/community/zeebe/play/rest/ProcessesResource.kt, src/main/resources/public/js/rest-client.js, src/main/resources/public/js/view-common.js, src/main/resources/public/js/view-process-instance.js, src/main/resources/public/js/view-process.js, src/test/kotlin/org/camunda/community/zeebe/play/ConnectorServiceTest.kt
Show a warning on the process or process instance page if the process references connector secrets that are not set yet.
The warning contains a button to add the missing secret. By clicking the button, it adds all missing secrets with the value `ENTER_YOUR_SECRET`.
related to #30
=> feat: Show warning if connector secrets are missing

src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorProperties.kt, src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorsConfig.kt, src/main/kotlin/org/camunda/community/zeebe/play/rest/ConnectorsResource.kt, src/main/resources/application.yml, src/main/resources/public/js/rest-client.js, src/main/resources/public/js/view-bpmn.js, src/main/resources/public/js/view-common.js, src/main/resources/public/js/view-process-instance.js, src/main/resources/templates/views/home.html
Change the way how connectors are integrated. Instead of running the connectors actively as job workers, the connectors can be invoked manually for a given job (i.e. passive mode). 
Create a new API to invoke a connector for a given job type and job key. 
related to #30
=> feat: Invoke connectors manually

src/main/resources/public/js/view-process-instance.js
This change replays the action of the "Set Variables" modal. This only works if the scope is set to global, because figuring out the scope key for non-globally scoped variables and correlating this with the equivalent scope key in the new instance is kinda tricky.
But I think globally scoped changes are the majority of use-cases for the "Set Variables" modal, so this should already make support much better.
closes #110
=> fix: replay manual globally scoped variable changes

src/main/resources/public/js/view-common.js, src/main/resources/public/js/view-process-instance.js, src/main/resources/templates/views/monitoring/process-instances/process-instance.html
Using the general time travel from the Set Variables menu created a history entry that just said "timeTravel" without any element information attached. This caused the replay to fail. With this fix, we replay the actual timeDefinition instead.
This might still produce inconsistent results when using a non-duration timeDefinition, but it should no longer block the replay of the history.
closes #108
=> fix: handle rewind replay for non-elemental time travel

src/main/resources/public/js/view-process-instance.js
When a user clicks on rewind, it terminates the current process instance. 
Assumption: the user doesn't want to continue the process instance after clicking on rewind. Instead, the user wants to play with the new process instance at the selected element.
By terminating the current process instance, we solve some issues with open message subscriptions.
related to #104
=> feat: Cancel process instance on rewind

pom.xml
Dump `connector-runtime-bundle` from `0.15.0` to `0.16.0`
=> deps: dump connector-runtime from 0.15.0 to 0.16.0

src/main/resources/public/js/view-bpmn.js, src/main/resources/public/js/view-common.js, src/main/resources/templates/views/modals/complete-job-modal.html
Change the primary action of jobs with cached responses. Instead of completing the job immediately with the previous response, open the complete job modal with the previous response.
Clear the job modal after submitting it.
=> feat: Show previous response before completing the job

src/main/resources/public/js/view-common.js
Fixes a typo in the incident retry popup.
closes #126
=> fix: Correct typo in incident retry popup

src/main/resources/public/js/view-common.js, src/main/resources/public/js/view-process-instance.js
* Applies the `resolveIncident` action when replaying the process instance
closes #118
=> fix: apply incident resolution when replaying actions for rewind

src/main/resources/public/js/view-process-instance.js
Show the same actions on the job action as on the diagram. 
- when completing a job, fill the variable field with the previous response 
- if a job is based on a connector, it can only be invoked but not completed/failed/error-thrown  
closes #122
=> fix: Align the actions in the job tab with the diagram

src/main/resources/public/js/view-bpmn.js, src/main/resources/public/js/view-process-instance.js
Fixing an issue that prevented the invocation of a connector from the BPMN diagram. 
If a job for a connector was active and the data were reloaded, the bottom of the connector didn't invoke the connector anymore. The issue was caused by multiple overlapping overlays for the same element.
Solving the issue by removing all overlays first.
=> fix: Can't invoke connector on the diagram

pom.xml
Dump `EZ` from `1.1.0` to [1.2.0-alpha4](https://github.com/camunda-community-hub/eze/releases/tag/1.2.0-alpha1).
This allows testing the newest features from Zeebe `8.2.0-alpha4` with Zeebe-Play.
=> deps: dump EZE from `1.1.0` to `1.2.0-alpha1`

src/main/resources/public/css/app.css, src/main/resources/public/js/incident-modal.js, src/main/resources/public/js/view-common.js, src/main/resources/public/js/view-process-instance.js, src/main/resources/public/js/view-process.js, src/main/resources/templates/fragments/footer.html, src/main/resources/templates/views/modals/complete-job-modal.html, src/main/resources/templates/views/modals/resolve-incident-modal.html, src/main/resources/templates/views/monitoring/process-instances/process-instance.html, src/main/resources/templates/views/new-instance-modal.html, src/main/resources/templates/views/publish-message-modal.html, src/main/resources/templates/views/set-variables-modal.html
This PR adds a modal that is opened when the user wants to resolve an incident. This modal contains the incident error message as well as a way to set variables before resolving the incident.
This PR also adds a notification when a new incident occurs with a clickable element that opens the incident tab.
This PR also removes the prefilled empty object in places where variables are specified and replaces it with a placeholder showing sample JSON to specify a single variable with a string value.
closes #134
=> feat: add "Resolve Incident" modal

pom.xml
Fix the DMN execution by aligning the dependency versions to Zeebe `8.2.0-alpha4`
- dump `zeebe-hazelcast-exporter` from `1.2.1` to `1.4.0-alpha1`
=> fix: DMN execution and record exporting

src/main/resources/public/js/zeeqs-client.js
This PR adds a close event handler to the GraphQL websocket connection that, when called, re-establishes the connection. My hope is that this solves #143.
I could not verify this yet as the websocket on my dev-setup does not timeout in the same way it does in production so I would keep the issue open until I was able to verify the fix on production.
related to #143
=> fix: re-establish GraphQL subscription after websocket close

src/main/resources/public/js/view-bpmn.js, src/main/resources/public/js/view-process-instance.js
Add a new option to complete a connector job without invoking the connector. Instead, the job is completed with the provided variables.
Related to https://github.com/camunda/product-hub/issues/969
=> feat: Complete connector job

pom.xml
- dump EZE from `1.2.0-alpha1` to [1.2.0-alpha2](https://github.com/camunda-community-hub/eze/releases/tag/1.2.0-alpha2) (Zeebe `8.2.0-alpha5`)
=> deps: dump EZE from 1.2.0-alpha1 to 1.2.0-alpha2

pom.xml, src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorService.kt, src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorsConfig.kt, src/main/kotlin/org/camunda/community/zeebe/play/rest/ConnectorsResource.kt
- dump connectors-bundle from 0.16.1 to 0.17.0 
- dump connector-sdk from 0.6.0 to 0.7.0
- adopt new connectors API
=> Dump connectors from 0.16.1 to 0.17.0

pom.xml
* Dump ZeeQS from `2.8.0` to [2.8.2](https://github.com/camunda-community-hub/zeeqs/releases/tag/2.8.2)
=> deps: dump zeeqs from 2.8.0 to 2.8.2

src/main/resources/templates/fragments/header.html, src/main/resources/templates/fragments/navbar.html, src/main/resources/templates/main.html, src/main/resources/templates/views/home.html
* When the URL contains "play.camunda.io", the "Zeebe Play" section of the header is replaced with just "Play" and the icons are removed
* The same applies to the page title
* In the "Demo process" tile on the home view, it then reads "Try out Play by using a demo process" instead of "Try out Zeebe Play by using a demo process"
* I removed the `p` tag in the card body for the status info in the home view as `p` tags cannot contain tables and this broke the auto-formatter.
closes #163
=> feat: Call it just "Play" in Camunda hosted instances

src/main/kotlin/org/camunda/community/zeebe/play/rest/DecisionsResource.kt, src/main/resources/public/css/app.css, src/main/resources/public/js/rest-client.js, src/main/resources/public/js/view-decision-evaluation.js, src/main/resources/public/js/view-decision.js, src/main/resources/templates/views/deployment/decision/decision.html, src/main/resources/templates/views/deployment/decision/evaluate-decision-modal.html, src/main/resources/templates/views/monitoring/decision-evaluations/decision-evaluation.html
- Add a new button to evaluate a decision on the decision view
- Cache the provided variables for the evaluation and provide them for the next evaluation
- On reset, provide sample variables for each decision input
closes #74
=> feat: Ad-hoc decision evaluation 

src/main/kotlin/org/camunda/community/zeebe/play/rest/ConnectorsResource.kt
Currently, the invocation of connector jobs doesn't work well if multiple jobs are active and the user clicks the button quickly. As a result, the jobs can't be invoked (i.e. not found). The root cause is https://github.com/camunda/zeebe/issues/5073.
Resolve the issue by removing the activation of the connector jobs. Instead, pass the job directly to the connector. Since the job is not activated, use the data from the state and build a fake job object.
=> fix: Invoke multiple connector jobs of the same type

src/main/resources/public/js/incident-modal.js, src/main/resources/public/js/mp_integration.js, src/main/resources/public/js/view-home.js, src/main/resources/public/js/view-process-instance.js, src/main/resources/public/js/view-process.js, src/main/resources/templates/fragments/footer.html
* Renamed tracking.js to mp_integration.js (short for mixpanel integration). Adblockers tend to block files called "tracking" or "mixpanel" purely based on filename
* used optional chaining to not fail if the global tracking function is not defined, e.g. if an adblocker still blocks the mp_integration file based on content.
closes #165
=> fix: mitigate adblocker issues

pom.xml
Dump `zeebe-hazelcast-exporter` from `1.4.0-alpha1` to [1.4.0](https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/releases/tag/1.4.0).
=> deps: dump hazelcast-exporter to 1.4.0

pom.xml
Dump `Zeeqs` from `2.8.2` to [2.9.0](https://github.com/camunda-community-hub/zeeqs/releases/tag/2.9.0).
=> deps: Dump Zeeqs from 2.8.2 to 2.9.0

src/main/resources/public/css/form-js.css
Update the `form-js.css` to `1.13.1`. The JS was updated already but the CSS was missing. As a result, the forms were not styled correctly.
closes #183 
related to #168
=> fix: Update form-js styles

pom.xml, src/main/kotlin/org/camunda/community/zeebe/play/ZeebePlayApplication.kt, src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorsConfig.kt, src/main/kotlin/org/camunda/community/zeebe/play/zeebe/RemoteZeebeConfig.kt, src/main/resources/application.yml, src/test/kotlin/org/camunda/community/zeebe/play/ApplicationTests.kt
* dump `spring-zeebe` from `8.1.17` to `8.2.0`
* dump `connectors-bundle` from `0.17.0` to `1.18`
* disable the Spring-Zeebe initialization (configuration issues with the embedded engine)
closes #181
=> feat: Update to Spring-Zeebe 8.2 and to connectors-bundle 1.18

src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorService.kt, src/test/kotlin/org/camunda/community/zeebe/play/ConnectorServiceTest.kt
Connector secrets can have dashes in their names. 
Adjust the regex to support secrets with dashed.
closes #119
=> fix: Connector secrets with dashes

src/main/kotlin/org/camunda/community/zeebe/play/rest/ConnectorsResource.kt
Fix the invocation of the SendGrid connector.
The connector failed to invoke because some parts of the integration were not implemented. Add the missing parts. :wrench: 
closes #192
=> fix: invoke SendGrid connector

src/main/kotlin/org/camunda/community/zeebe/play/rest/DeploymentsResource.kt, src/main/resources/public/js/rest-client.js, src/main/resources/public/js/view-deployment.js, src/test/kotlin/org/camunda/community/zeebe/play/DeploymentTest.kt, src/test/kotlin/resources/rating.dmn
Add a new API to deploy with resources (`/rest/deployments/deploy`). Keep the old API for backward compatibility with the Web Modeler (`/rest/deployments/`).
Compared to the old API, it returns an enhanced response with all deployed resources.
```json
{
"deploymentKey": 2251799813685252,
"deployedProcesses": [
{
"processKey": 2251799813685249,
"bpmnProcessId": "template-absence-request",
"resourceName": "absence-request_v4.bpmn",
"isDuplicate": false
}
],
"deployedDecisions": [
{
"decisionKey": 2251799813685251,
"decisionId": "department_line_manager",
"resourceName": "department_line_manager.dmn",
"isDuplicate": false
}
]
}
```
If a resource was already deployed, it still returns the resource and marks it as duplicated.
```json
{
"deploymentKey": 2251799813685254,
"deployedProcesses": [ …
```
=> fix: Enhanced deployment response

src/main/resources/public/js/view-bpmn.js
Quotation marks in element info tooltips broke the HTML so the info was not rendered correctly. This PR encodes those quotation marks.
closes #184
=> fix: encode quotation marks for element info tooltips

src/main/resources/public/css/app.css
Long variables broke the layout, not only in the incident modal, but also in the variables tab. I decided to add the rule to the general `code` tag in alignment with the rules established by Bootstrap here: 
https://github.com/camunda-community-hub/zeebe-play/blob/bdcf7c08ce4a14f3b132ca6c610f72740fc0ce9a/src/main/resources/public/css/bootstrap-reboot.css#L268-L272
contributes to #193
=> fix: break long variable values in code blocks

src/main/resources/public/css/app.css, src/main/resources/public/js/view-common.js
- Removes the info icons for sequence flows because they can be misplaced
- De-emphasizes all other info icons to no longer compete for attention with the primary CTAs like the start instance button
Closes #213
=> fix: remove misplaced condition expression info icons

src/main/resources/public/css/app.css, src/main/resources/public/js/view-process-instance.js
If the process has no completed jobs yet, buttons that complete a job pulsate slightly to draw the users attention to them
closes #218
=> feat: pulsate play buttons on new process instances

pom.xml, src/main/kotlin/org/camunda/community/zeebe/play/ZeebePlayApplication.kt, src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorService.kt, src/main/kotlin/org/camunda/community/zeebe/play/connectors/ConnectorsConfig.kt, src/main/kotlin/org/camunda/community/zeebe/play/rest/ConnectorsResource.kt, src/main/resources/application.yml
Replace the dependency to `spring-zeebe-starter` and to the Camunda connector artifacts with the new recommended `spring-boot-starter-camunda-connectors` in version `0.20.0`.
Disable the inbound and outbound connectors in the configuration.
=> feat: Update connectors-bundle to 0.20.0

pom.xml, src/main/kotlin/org/camunda/community/zeebe/play/ZeebePlayApplication.kt, src/main/kotlin/org/camunda/community/zeebe/play/actuators/HazelcastReadinessIndicator.kt, src/main/kotlin/org/camunda/community/zeebe/play/actuators/ZeebeEngineReadinessIndicator.kt, src/main/kotlin/org/camunda/community/zeebe/play/services/HazelcastService.kt, src/main/kotlin/org/camunda/community/zeebe/play/zeebe/EmbeddedZeebeConfig.kt, src/main/kotlin/org/camunda/community/zeebe/play/zeebe/RemoteZeebeConfig.kt, src/main/kotlin/org/camunda/community/zeebe/play/zeebe/ZeebeService.kt, src/main/resources/application.yml
* Add Spring Boot Actuator 
* Enable health and metrics endpoint
* Include a Zeebe engine and a Hazelcast status check to the readiness probe
Liveness:
```
// request:
http://localhost:8080/actuator/health/liveness
// response:
{"status":"UP"}
```
Readiness:
```
// request:
http://localhost:8080/actuator/health/readiness
// response:
{"status":"UP","components":{"hazelcastReadinessIndicator":{"status":"UP"},"readinessState":{"status":"UP"},"zeebeEngineReadinessIndicator":{"status":"UP"}}}
```
=> feat: Add health probes and metrics

src/main/resources/public/js/incident-modal.js, src/main/resources/public/js/view-connectors.js, src/main/resources/public/js/view-process-instance.js
This change prevents HTML injection for variable names and connector secrets. For the tables this was achieved by targeting the empty container element via jQuery and adding the content as text instead of adding it as HTML.
I removed the variable payload from the notifications as I don't think it's needed there.
closes #248
=> fix: handle variable and secret values as text
